import { z } from "zod";

/**
 * Phase 11 input schemas (notifications + messaging). `.strict()` everywhere:
 * an unexpected field — a smuggled `userId`, `senderId`, `recipientId`,
 * `role` — is rejected instead of being silently ignored, so identity can
 * only ever come from the session.
 */

const recordId = (label: string) =>
  z
    .string({ required_error: `${label} is required` })
    .trim()
    .min(1, `${label} is required`)
    .max(64, `${label} is invalid`)
    .regex(/^[A-Za-z0-9_-]+$/, `${label} is invalid`);

const cursor = z
  .string()
  .trim()
  .min(1)
  .max(200)
  .regex(/^[A-Za-z0-9_-]+$/, "Invalid cursor");

const pageLimit = (max: number) => z.number().int().min(1).max(max);

export const MAX_MESSAGE_LENGTH = 2000;

/** Plain text only. Trimmed; empty / whitespace-only rejected; NUL bytes rejected (Postgres text cannot store them). */
export const messageContentSchema = z
  .string({ required_error: "Message is required" })
  .trim()
  .min(1, "Message can't be empty.")
  .max(MAX_MESSAGE_LENGTH, `Message must be ${MAX_MESSAGE_LENGTH} characters or fewer.`)
  .refine((value) => !value.includes("\u0000"), "Message contains invalid characters.");

export const listNotificationsSchema = z
  .object({
    cursor: cursor.optional(),
    limit: pageLimit(50).optional(),
    unreadOnly: z.boolean().optional(),
  })
  .strict();

export const notificationIdSchema = z.object({ notificationId: recordId("Notification") }).strict();

export const courseSlugSchema = z
  .object({
    courseSlug: z
      .string({ required_error: "Course is required" })
      .trim()
      .min(1)
      .max(160)
      .regex(/^[A-Za-z0-9][A-Za-z0-9-]*$/, "Course is invalid"),
  })
  .strict();

export const listConversationsSchema = z.object({ limit: pageLimit(50).optional() }).strict();

export const conversationMessagesSchema = z
  .object({
    conversationId: recordId("Conversation"),
    cursor: cursor.optional(),
    limit: pageLimit(50).optional(),
  })
  .strict();

export const sendMessageSchema = z
  .object({
    conversationId: recordId("Conversation"),
    content: messageContentSchema,
    // Generated by the browser for each composed message; a retry re-sends the
    // SAME key, which is what makes the send idempotent.
    clientMessageId: z
      .string({ required_error: "Message id is required" })
      .trim()
      .min(8)
      .max(64)
      .regex(/^[A-Za-z0-9_-]+$/, "Message id is invalid"),
  })
  .strict();

export const markConversationReadSchema = z
  .object({
    conversationId: recordId("Conversation"),
    upToMessageId: recordId("Message").optional(),
  })
  .strict();
