/**
 * Development/sample database seed.
 *
 * This is sample data for local development only — it exists so the real
 * database has something to query while the frontend still reads from
 * src/data/mock.ts for the parts not yet migrated. It intentionally
 * mirrors that mock data's flavor (same categories/instructors feel)
 * without being a 1:1 copy, and it does NOT replace mock.ts yet.
 *
 * Run with: npm run db:seed
 */
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";

// Generated by `npm run db:generate` — see prisma/schema.prisma.
import { Prisma, PrismaClient } from "../src/generated/prisma/client";
import { computeEarningSplit } from "../src/server/config/finance-policy";

// Seeding does a lot of sequential upserts; run it against the direct
// connection to avoid any pooler/transaction-mode quirks, falling back to
// DATABASE_URL for setups with no separate pooled connection.
const connectionString = process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"];

/**
 * This seed creates accounts with KNOWN passwords (including an ADMIN). It must
 * never run against a real deployment by accident. It refuses to run when
 * NODE_ENV=production or when the database host is not local, unless
 * ALLOW_DEMO_SEED=true is set on purpose (e.g. a throwaway cloud demo/test DB).
 * For a real production admin account use `npm run admin:create` instead.
 */
function assertSeedAllowed() {
  if (process.env["ALLOW_DEMO_SEED"] === "true") return;
  let host = "";
  try {
    host = new URL(connectionString ?? "").hostname;
  } catch {
    // Unparseable/missing URL: let Prisma report the real connection problem.
    return;
  }
  const isLocal = ["localhost", "127.0.0.1", "::1", "[::1]", "host.docker.internal"].includes(host);
  if (process.env["NODE_ENV"] === "production" || !isLocal) {
    console.error(
      "Refusing to run the DEMO seed: it creates accounts with known passwords (including an admin).\n" +
        `  NODE_ENV=${process.env["NODE_ENV"] ?? "(unset)"}, database host is ${isLocal ? "local" : "NOT local"}.\n` +
        "  - Local development: point DIRECT_URL/DATABASE_URL at a local PostgreSQL.\n" +
        "  - Throwaway cloud demo/test database only: re-run with ALLOW_DEMO_SEED=true.\n" +
        "  - Real production admin account: use `npm run admin:create`.",
    );
    process.exit(1);
  }
}
assertSeedAllowed();

const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

async function hash(password: string) {
  return bcrypt.hash(password, 10);
}

const REVIEW_COMMENTS: Record<number, string[]> = {
  5: [
    "Clear explanations and practical examples throughout.",
    "Best course I've taken on this topic — genuinely changed how I work.",
    "The projects made everything click. Highly recommend.",
  ],
  4: [
    "Solid course overall, a couple of sections could go deeper.",
    "Well structured and easy to follow at my own pace.",
  ],
  3: ["Good content but the pacing felt uneven in places."],
  2: ["Useful information but assumed more prior knowledge than advertised."],
};

function ratingFor(studentIndex: number, courseIndex: number): number {
  const pattern = [5, 4, 5, 3, 4, 5, 5, 4, 2, 5, 4, 5];
  return pattern[(studentIndex * 5 + courseIndex * 3) % pattern.length] ?? 5;
}

async function main() {
  console.log("Seeding Learnora database...");

  // -- Categories ----------------------------------------------------------
  const categoryDefs = [
    {
      slug: "web-development",
      name: "Web Development",
      description: "Frontend to full-stack",
      icon: "Code2",
    },
    {
      slug: "programming",
      name: "Programming",
      description: "Languages and fundamentals",
      icon: "Terminal",
    },
    {
      slug: "data-science",
      name: "Data Science",
      description: "Statistics, Python, ML",
      icon: "LineChart",
    },
    {
      slug: "design",
      name: "UI / UX Design",
      description: "Research to design systems",
      icon: "PenTool",
    },
    {
      slug: "business",
      name: "Business",
      description: "Strategy and leadership",
      icon: "Briefcase",
    },
  ];
  const categories = new Map<string, Awaited<ReturnType<typeof prisma.category.upsert>>>();
  for (const def of categoryDefs) {
    const category = await prisma.category.upsert({
      where: { slug: def.slug },
      update: {},
      create: def,
    });
    categories.set(def.slug, category);
  }

  // -- Admin -----------------------------------------------------------------
  await prisma.user.upsert({
    where: { email: "admin@learnora.dev" },
    update: {},
    create: {
      name: "Amina Rahman",
      email: "admin@learnora.dev",
      passwordHash: await hash("Admin123!"),
      role: "ADMIN",
      emailVerified: true,
    },
  });

  // -- Instructors -------------------------------------------------------
  const instructorDefs = [
    {
      email: "elena.vasquez@learnora.dev",
      name: "Elena Vasquez",
      headline: "Principal Frontend Engineer, Meridian Labs",
      bio: "Twelve years building interface platforms for design-led product teams. Leads the frontend guild at Meridian Labs.",
      expertise: ["React", "TypeScript", "Design Systems"],
      approvalStatus: "APPROVED" as const,
    },
    {
      email: "marcus.chen@learnora.dev",
      name: "Marcus Chen",
      headline: "Staff Data Scientist",
      bio: "Focused on applied machine learning and statistics education, with a decade in production ML systems.",
      expertise: ["Python", "Machine Learning", "Statistics"],
      approvalStatus: "APPROVED" as const,
    },
    {
      email: "priyanka.das@learnora.dev",
      name: "Priyanka Das",
      headline: "Backend Engineer",
      bio: "Applied for instructor access recently — still awaiting admin approval.",
      expertise: ["Node.js", "Databases"],
      approvalStatus: "PENDING" as const,
    },
  ];
  const instructors = [];
  for (const def of instructorDefs) {
    const user = await prisma.user.upsert({
      where: { email: def.email },
      update: {},
      create: {
        name: def.name,
        email: def.email,
        passwordHash: await hash("Instructor123!"),
        role: "INSTRUCTOR",
        emailVerified: true,
        instructorProfile: {
          create: {
            headline: def.headline,
            bio: def.bio,
            expertise: def.expertise,
            approvalStatus: def.approvalStatus,
            approvedAt: def.approvalStatus === "APPROVED" ? new Date() : null,
          },
        },
      },
    });
    instructors.push(user);
  }
  const [elena, marcus] = instructors;

  // -- Students ------------------------------------------------------------
  const studentDefs = [
    { email: "sara.khan@learnora.dev", name: "Sara Khan", headline: "Frontend Developer" },
    { email: "james.oconnor@learnora.dev", name: "James O'Connor", headline: "Product Manager" },
    { email: "priya.nair@learnora.dev", name: "Priya Nair", headline: "Data Analyst" },
  ];
  const students = [];
  for (const def of studentDefs) {
    const user = await prisma.user.upsert({
      where: { email: def.email },
      update: {},
      create: {
        name: def.name,
        email: def.email,
        passwordHash: await hash("Student123!"),
        role: "STUDENT",
        emailVerified: true,
        studentProfile: {
          create: { headline: def.headline, interests: ["Web Development", "Data Science"] },
        },
      },
    });
    students.push(user);
  }

  // -- Courses, sections, lessons ------------------------------------------
  type LessonDef = {
    title: string;
    type: "VIDEO" | "ARTICLE" | "QUIZ";
    duration: number;
    isPreview?: boolean;
  };
  type SectionDef = { title: string; lessons: LessonDef[] };
  type CourseDef = {
    slug: string;
    title: string;
    subtitle: string;
    categorySlug: string;
    instructorId: string;
    level: "BEGINNER" | "INTERMEDIATE" | "ADVANCED" | "ALL_LEVELS";
    status: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "REJECTED";
    rejectionReason?: string;
    featured: boolean;
    price: number;
    discountPrice?: number;
    sections: SectionDef[];
  };

  const courseDefs: CourseDef[] = [
    {
      slug: "modern-react-typescript",
      title: "Modern React & TypeScript",
      subtitle: "Build production interfaces with confident types and clean state.",
      categorySlug: "web-development",
      instructorId: elena!.id,
      level: "INTERMEDIATE",
      status: "PUBLISHED",
      featured: true,
      price: 79.99,
      discountPrice: 49.99,
      sections: [
        {
          title: "Getting Started",
          lessons: [
            { title: "Course Overview", type: "VIDEO", duration: 300, isPreview: true },
            { title: "Environment Setup", type: "VIDEO", duration: 480 },
          ],
        },
        {
          title: "Component Patterns",
          lessons: [
            { title: "Typed Props & Children", type: "VIDEO", duration: 620 },
            { title: "Knowledge Check", type: "QUIZ", duration: 300 },
          ],
        },
      ],
    },
    {
      slug: "advanced-typescript-patterns",
      title: "Advanced TypeScript Patterns",
      subtitle: "Generics, conditional types and building type-safe APIs.",
      categorySlug: "web-development",
      instructorId: elena!.id,
      level: "ADVANCED",
      status: "PUBLISHED",
      featured: false,
      price: 94.99,
      sections: [
        {
          title: "Type-Level Programming",
          lessons: [
            { title: "Conditional & Mapped Types", type: "VIDEO", duration: 720, isPreview: true },
            { title: "Building a Type-Safe Router", type: "VIDEO", duration: 900 },
          ],
        },
      ],
    },
    {
      slug: "programming-fundamentals-js",
      title: "Programming Fundamentals with JavaScript",
      subtitle: "Variables, control flow and functions — the real foundation.",
      categorySlug: "programming",
      instructorId: elena!.id,
      level: "BEGINNER",
      status: "PUBLISHED",
      featured: false,
      price: 0,
      sections: [
        {
          title: "The Basics",
          lessons: [
            { title: "Values & Variables", type: "VIDEO", duration: 360, isPreview: true },
            { title: "Functions & Scope", type: "VIDEO", duration: 480 },
            { title: "Practice Quiz", type: "QUIZ", duration: 240 },
          ],
        },
      ],
    },
    {
      slug: "python-for-data-science",
      title: "Python for Data Science",
      subtitle: "From pandas basics to your first ML model.",
      categorySlug: "data-science",
      instructorId: marcus!.id,
      level: "BEGINNER",
      status: "PUBLISHED",
      featured: true,
      price: 34.99,
      sections: [
        {
          title: "Python Foundations",
          lessons: [
            { title: "Why Python for Data", type: "VIDEO", duration: 360, isPreview: true },
            { title: "NumPy & pandas Basics", type: "VIDEO", duration: 900 },
          ],
        },
      ],
    },
    {
      slug: "machine-learning-foundations",
      title: "Machine Learning Foundations",
      subtitle: "Core algorithms and how to evaluate them honestly.",
      categorySlug: "data-science",
      instructorId: marcus!.id,
      level: "INTERMEDIATE",
      status: "PUBLISHED",
      featured: false,
      price: 64.99,
      sections: [
        {
          title: "Supervised Learning",
          lessons: [
            {
              title: "Regression vs Classification",
              type: "VIDEO",
              duration: 540,
              isPreview: true,
            },
            { title: "Model Evaluation", type: "ARTICLE", duration: 300 },
          ],
        },
      ],
    },
    {
      slug: "design-systems-fundamentals",
      title: "Design Systems Fundamentals",
      subtitle: "Tokens, components and documentation that scale.",
      categorySlug: "design",
      instructorId: elena!.id,
      level: "INTERMEDIATE",
      status: "PUBLISHED",
      featured: true,
      price: 84.99,
      discountPrice: 59.99,
      sections: [
        {
          title: "Foundations",
          lessons: [
            { title: "Design Tokens", type: "VIDEO", duration: 420, isPreview: true },
            { title: "Component API Design", type: "VIDEO", duration: 600 },
          ],
        },
      ],
    },
    {
      slug: "product-strategy-for-engineers",
      title: "Product Strategy for Engineers",
      subtitle: "Make better roadmap and prioritisation calls.",
      categorySlug: "business",
      instructorId: marcus!.id,
      level: "ALL_LEVELS",
      status: "PUBLISHED",
      featured: false,
      price: 44.99,
      sections: [
        {
          title: "Thinking in Bets",
          lessons: [
            { title: "Prioritisation Frameworks", type: "VIDEO", duration: 480, isPreview: true },
            { title: "Writing a One-Pager", type: "ARTICLE", duration: 240 },
          ],
        },
      ],
    },
    {
      slug: "ux-research-methods",
      title: "UX Research Methods",
      subtitle: "Interviews, usability testing and turning findings into decisions.",
      categorySlug: "design",
      instructorId: marcus!.id,
      level: "BEGINNER",
      status: "DRAFT",
      featured: false,
      price: 39.99,
      sections: [
        {
          title: "Planning Research",
          lessons: [{ title: "Choosing a Method", type: "VIDEO", duration: 360, isPreview: true }],
        },
      ],
    },
    {
      slug: "node-backend-fundamentals",
      title: "Node.js Backend Fundamentals",
      subtitle: "REST APIs, authentication and database design with Node.js.",
      categorySlug: "web-development",
      instructorId: elena!.id,
      level: "INTERMEDIATE",
      status: "PENDING_REVIEW",
      featured: false,
      price: 54.99,
      sections: [
        {
          title: "Building the API",
          lessons: [
            { title: "Setting Up Express", type: "VIDEO", duration: 420, isPreview: true },
            { title: "Connecting a Database", type: "VIDEO", duration: 540 },
          ],
        },
      ],
    },
    {
      slug: "intro-to-figma",
      title: "Intro to Figma",
      subtitle: "Design your first interface from scratch.",
      categorySlug: "design",
      instructorId: elena!.id,
      level: "BEGINNER",
      status: "REJECTED",
      rejectionReason:
        "The curriculum only has one short lesson — please add a full set of sections covering the basics through to a complete design project before resubmitting.",
      featured: false,
      price: 29.99,
      sections: [
        {
          title: "Getting Started",
          lessons: [
            { title: "The Figma Interface", type: "VIDEO", duration: 300, isPreview: true },
          ],
        },
      ],
    },
  ];

  const courses = [];
  for (const def of courseDefs) {
    const category = categories.get(def.categorySlug)!;
    const course = await prisma.course.upsert({
      where: { slug: def.slug },
      update: {},
      create: {
        title: def.title,
        slug: def.slug,
        subtitle: def.subtitle,
        description: def.subtitle,
        level: def.level,
        price: def.price,
        ...(def.discountPrice !== undefined && { discountPrice: def.discountPrice }),
        status: def.status,
        publishedAt: def.status === "PUBLISHED" ? new Date() : null,
        submittedAt:
          def.status === "PENDING_REVIEW" || def.status === "REJECTED" ? new Date() : null,
        rejectionReason:
          def.status === "REJECTED" ? (def.rejectionReason ?? "Needs more work.") : null,
        featured: def.featured,
        requirements: ["Basic computer literacy"],
        learningOutcomes: ["Build real projects", "Understand core concepts"],
        targetAudience: ["Beginners", "Career switchers"],
        instructor: { connect: { id: def.instructorId } },
        category: { connect: { id: category.id } },
        sections: {
          create: def.sections.map((section, sectionIndex) => ({
            title: section.title,
            position: sectionIndex,
            lessons: {
              create: section.lessons.map((lesson, lessonIndex) => ({
                title: lesson.title,
                type: lesson.type,
                duration: lesson.duration,
                position: lessonIndex,
                isPreview: lesson.isPreview ?? false,
              })),
            },
          })),
        },
      },
    });
    courses.push({ ...course, status: def.status });
  }

  // -- Enrollments & reviews (published courses only) ----------------------
  const publishedCourses = courses.filter((c) => c.status === "PUBLISHED");
  for (let studentIndex = 0; studentIndex < students.length; studentIndex++) {
    const student = students[studentIndex]!;
    for (let courseIndex = 0; courseIndex < publishedCourses.length; courseIndex++) {
      const course = publishedCourses[courseIndex]!;

      await prisma.enrollment.upsert({
        where: { userId_courseId: { userId: student.id, courseId: course.id } },
        update: {},
        create: { userId: student.id, courseId: course.id },
      });

      const rating = ratingFor(studentIndex, courseIndex);
      const comments = REVIEW_COMMENTS[rating] ?? REVIEW_COMMENTS[5]!;
      const comment = comments[courseIndex % comments.length]!;

      await prisma.review.upsert({
        where: { userId_courseId: { userId: student.id, courseId: course.id } },
        update: {},
        create: { userId: student.id, courseId: course.id, rating, comment },
      });
    }
  }

  // -- Lesson progress: give a couple of students realistic in-progress /
  // completed states so My Learning and the course player have something
  // to show beyond "0% everywhere". ------------------------------------
  const sara = students[0]!;
  const james = students[1]!;
  // priya (students[2]) is left with zero lesson progress on purpose, to
  // exercise the "not started yet" state.

  async function lessonsOf(courseId: string) {
    const sections = await prisma.courseSection.findMany({
      where: { courseId },
      orderBy: { position: "asc" },
      include: { lessons: { orderBy: { position: "asc" } } },
    });
    return sections.flatMap((s) => s.lessons);
  }

  const reactCourse = publishedCourses.find((c) => c.slug === "modern-react-typescript");
  const pythonCourse = publishedCourses.find((c) => c.slug === "python-for-data-science");
  const advancedTsCourse = publishedCourses.find((c) => c.slug === "advanced-typescript-patterns");

  if (reactCourse) {
    // Sara has finished this course entirely.
    const lessons = await lessonsOf(reactCourse.id);
    const enrollment = await prisma.enrollment.findUniqueOrThrow({
      where: { userId_courseId: { userId: sara.id, courseId: reactCourse.id } },
    });
    for (const lesson of lessons) {
      await prisma.lessonProgress.upsert({
        where: { enrollmentId_lessonId: { enrollmentId: enrollment.id, lessonId: lesson.id } },
        update: {},
        create: {
          enrollmentId: enrollment.id,
          lessonId: lesson.id,
          completed: true,
          progressPercent: 100,
        },
      });
    }
    await prisma.enrollment.update({
      where: { id: enrollment.id },
      data: { status: "COMPLETED", completedAt: new Date(), lastAccessedAt: new Date() },
    });
  }

  if (pythonCourse) {
    // Sara is partway through this one — completed the first lesson only.
    const lessons = await lessonsOf(pythonCourse.id);
    const first = lessons[0];
    const enrollment = await prisma.enrollment.findUniqueOrThrow({
      where: { userId_courseId: { userId: sara.id, courseId: pythonCourse.id } },
    });
    if (first) {
      await prisma.lessonProgress.upsert({
        where: { enrollmentId_lessonId: { enrollmentId: enrollment.id, lessonId: first.id } },
        update: {},
        create: {
          enrollmentId: enrollment.id,
          lessonId: first.id,
          completed: true,
          progressPercent: 100,
        },
      });
    }
    await prisma.enrollment.update({
      where: { id: enrollment.id },
      data: { lastAccessedAt: new Date() },
    });
  }

  if (advancedTsCourse) {
    // James has just started this one.
    const lessons = await lessonsOf(advancedTsCourse.id);
    const first = lessons[0];
    const enrollment = await prisma.enrollment.findUniqueOrThrow({
      where: { userId_courseId: { userId: james.id, courseId: advancedTsCourse.id } },
    });
    if (first) {
      await prisma.lessonProgress.upsert({
        where: { enrollmentId_lessonId: { enrollmentId: enrollment.id, lessonId: first.id } },
        update: {},
        create: {
          enrollmentId: enrollment.id,
          lessonId: first.id,
          completed: true,
          progressPercent: 100,
        },
      });
    }
    await prisma.enrollment.update({
      where: { id: enrollment.id },
      data: { lastAccessedAt: new Date() },
    });
  }

  // -- Wishlist --------------------------------------------------------------
  const wishlistDefs: { student: (typeof students)[number]; slug: string }[] = [
    { student: sara, slug: "design-systems-fundamentals" },
    { student: sara, slug: "machine-learning-foundations" },
    { student: james, slug: "python-for-data-science" },
  ];
  for (const def of wishlistDefs) {
    const course = publishedCourses.find((c) => c.slug === def.slug);
    if (!course) continue;
    await prisma.wishlist.upsert({
      where: { userId_courseId: { userId: def.student.id, courseId: course.id } },
      update: {},
      create: { userId: def.student.id, courseId: course.id },
    });
  }

  // -- Phase 10 sample finance data (idempotent) ------------------------------
  // A few CONSISTENT paid purchases (Order + OrderItem + Payment + Enrollment +
  // InstructorEarning, split via the same finance policy the app uses) so the
  // earnings / refund / payout screens have something to show immediately:
  //   SEED0001  Sara  -> Advanced TypeScript (Elena): AVAILABLE, refundable, payable
  //   SEED0002  James -> Python for Data Science (Marcus): AVAILABLE, below the minimum payout
  //   SEED0003/4 Priya/James -> ML Foundations / Product Strategy (Marcus): RESERVED in a PENDING payout
  // Each order is keyed by its fixed orderNumber and skipped entirely if it
  // already exists (so re-running the seed never duplicates or resets rows
  // you have since refunded/paid), or if the student already holds a PAID
  // order for that course.
  const financeSamples = [
    {
      n: "SEED0001",
      student: "sara.khan@learnora.dev",
      slug: "advanced-typescript-patterns",
      payout: null,
    },
    {
      n: "SEED0002",
      student: "james.oconnor@learnora.dev",
      slug: "python-for-data-science",
      payout: null,
    },
    {
      n: "SEED0003",
      student: "priya.nair@learnora.dev",
      slug: "machine-learning-foundations",
      payout: "LRN-PAY-SEED0001",
    },
    {
      n: "SEED0004",
      student: "james.oconnor@learnora.dev",
      slug: "product-strategy-for-engineers",
      payout: "LRN-PAY-SEED0001",
    },
  ] as const;
  const seededPayoutEarnings: { instructorId: string; earningId: string; net: Prisma.Decimal }[] =
    [];
  for (const sample of financeSamples) {
    const orderNumber = `LRN-ORD-${sample.n}`;
    if (await prisma.order.findUnique({ where: { orderNumber } })) continue;
    const buyer = await prisma.user.findUnique({ where: { email: sample.student } });
    const course = await prisma.course.findUnique({ where: { slug: sample.slug } });
    if (!buyer || !course || course.status !== "PUBLISHED") continue;
    const alreadyPaid = await prisma.order.count({
      where: { userId: buyer.id, status: "PAID", items: { some: { courseId: course.id } } },
    });
    if (alreadyPaid > 0) continue;

    const amount = course.discountPrice ?? course.price;
    const split = computeEarningSplit(amount);
    await prisma.$transaction(async (tx) => {
      const order = await tx.order.create({
        data: {
          userId: buyer.id,
          orderNumber,
          amount,
          currency: "USD",
          status: "PAID",
          items: { create: { courseId: course.id, price: amount } },
        },
        include: { items: true },
      });
      await tx.payment.create({
        data: {
          orderId: order.id,
          amount,
          currency: "USD",
          status: "PAID",
          provider: "simulated",
          externalReference: `SIM-SEED-${sample.n}`,
        },
      });
      const enrollment = await tx.enrollment.findUnique({
        where: { userId_courseId: { userId: buyer.id, courseId: course.id } },
      });
      if (!enrollment)
        await tx.enrollment.create({ data: { userId: buyer.id, courseId: course.id } });
      const earning = await tx.instructorEarning.create({
        data: {
          instructorId: course.instructorId,
          orderItemId: order.items[0]!.id,
          grossAmount: split.grossAmount,
          commissionRate: split.commissionRate,
          netAmount: split.netAmount,
          status: "AVAILABLE",
        },
      });
      if (sample.payout) {
        seededPayoutEarnings.push({
          instructorId: course.instructorId,
          earningId: earning.id,
          net: split.netAmount,
        });
      }
    });
  }
  if (seededPayoutEarnings.length > 0) {
    const first = seededPayoutEarnings[0]!;
    const total = seededPayoutEarnings.reduce((sum, e) => sum.plus(e.net), new Prisma.Decimal(0));
    await prisma.$transaction(async (tx) => {
      const payout = await tx.payout.create({
        data: {
          instructorId: first.instructorId,
          amount: total,
          currency: "USD",
          status: "PENDING",
          method: "SIMULATED",
          reference: "LRN-PAY-SEED0001",
        },
      });
      await tx.instructorEarning.updateMany({
        where: { id: { in: seededPayoutEarnings.map((e) => e.earningId) } },
        data: { status: "RESERVED", payoutId: payout.id },
      });
    });
  }

  // -- Phase 11 sample communication data (idempotent) ------------------------
  // One course conversation (Sara <-> Elena, about Advanced TypeScript) with
  // messages from both sides — the last one from Elena is UNREAD for Sara —
  // plus a few notifications in mixed read/unread states. Every row is keyed
  // (Conversation UNIQUE(courseId, studentId), Message clientMessageId,
  // Notification eventKey), so re-running the seed never duplicates anything,
  // and it never touches conversations/notifications you created yourself.
  // No sensitive data: only greetings and a generic announcement.
  {
    const sara = await prisma.user.findUnique({ where: { email: "sara.khan@learnora.dev" } });
    const elena = await prisma.user.findUnique({ where: { email: "elena.vasquez@learnora.dev" } });
    const adminUser = await prisma.user.findUnique({ where: { email: "admin@learnora.dev" } });
    const tsCourse = await prisma.course.findUnique({
      where: { slug: "advanced-typescript-patterns" },
    });
    const hasAccess =
      sara && tsCourse
        ? await prisma.enrollment.findFirst({
            where: {
              userId: sara.id,
              courseId: tsCourse.id,
              status: { in: ["ACTIVE", "COMPLETED"] },
            },
          })
        : null;

    if (sara && elena && tsCourse && hasAccess && tsCourse.instructorId === elena.id) {
      const conversation =
        (await prisma.conversation.findUnique({
          where: { courseId_studentId: { courseId: tsCourse.id, studentId: sara.id } },
        })) ??
        (await prisma.conversation.create({
          data: {
            courseId: tsCourse.id,
            studentId: sara.id,
            participants: { create: [{ userId: sara.id }, { userId: elena.id }] },
          },
        }));

      const now = Date.now();
      const script = [
        {
          key: "seed-msg-1",
          from: sara.id,
          text: "Hi Elena — quick question about the conditional types lesson. When should I prefer infer over a generic parameter?",
          ago: 180,
        },
        {
          key: "seed-msg-2",
          from: elena.id,
          text: "Hi Sara! Use infer when you need to extract a type from inside another type, and a generic parameter when the caller supplies it.",
          ago: 120,
        },
        {
          key: "seed-msg-3",
          from: elena.id,
          text: "Happy to look at an example if you paste one — this is easier to see in code.",
          ago: 90,
        },
      ] as const;
      let lastAt: Date | null = null;
      for (const m of script) {
        const exists = await prisma.message.findUnique({
          where: { senderId_clientMessageId: { senderId: m.from, clientMessageId: m.key } },
        });
        if (exists) continue;
        const createdAt = new Date(now - m.ago * 60_000);
        const created = await prisma.message.create({
          data: {
            conversationId: conversation.id,
            senderId: m.from,
            content: m.text,
            clientMessageId: m.key,
            createdAt,
          },
        });
        lastAt = createdAt;
        const recipientId = m.from === sara.id ? elena.id : sara.id;
        const recipientPath =
          recipientId === elena.id ? "/instructor/messages" : "/student/messages";
        await prisma.notification.createMany({
          data: [
            {
              userId: recipientId,
              type: "NEW_MESSAGE",
              title: `New message from ${m.from === sara.id ? sara.name : elena.name}`,
              message: `About “${tsCourse.title}”.`,
              link: `${recipientPath}?c=${conversation.id}`,
              eventKey: `message:${created.id}`,
              // Elena has "read" Sara's message (she replied); Sara's are left unread.
              readAt: recipientId === elena.id ? new Date(now - 100 * 60_000) : null,
              createdAt,
            },
          ],
          skipDuplicates: true,
        });
      }
      if (lastAt) {
        await prisma.conversation.updateMany({
          where: {
            id: conversation.id,
            OR: [{ lastMessageAt: null }, { lastMessageAt: { lt: lastAt } }],
          },
          data: { lastMessageAt: lastAt },
        });
        // Elena has read the thread up to Sara's message; Sara has not opened it yet.
        await prisma.conversationParticipant.updateMany({
          where: { conversationId: conversation.id, userId: elena.id, lastReadAt: null },
          data: { lastReadAt: new Date(now - 100 * 60_000) },
        });
      }
    }

    // Payment / payout notifications matching the Phase 10 sample finance rows (same eventKeys the app uses).
    for (const n of ["SEED0001", "SEED0002", "SEED0003", "SEED0004"]) {
      const order = await prisma.order.findUnique({
        where: { orderNumber: `LRN-ORD-${n}` },
        include: { items: { include: { course: { select: { title: true } } } } },
      });
      if (!order) continue;
      await prisma.notification.createMany({
        data: [
          {
            userId: order.userId,
            type: "PAYMENT",
            title: "Payment successful",
            message: `Your payment of USD ${order.amount.toFixed(2)} for “${order.items[0]?.course.title ?? "your course"}” went through (order ${order.orderNumber}). You now have access to the course.`,
            link: "/student/purchases",
            eventKey: `payment:${order.id}`,
            readAt: n === "SEED0001" ? null : new Date(),
          },
        ],
        skipDuplicates: true,
      });
    }
    const seededPayout = await prisma.payout.findUnique({
      where: { reference: "LRN-PAY-SEED0001" },
    });
    if (seededPayout) {
      await prisma.notification.createMany({
        data: [
          {
            userId: seededPayout.instructorId,
            type: "PAYOUT",
            title: "Payout requested",
            message: `Your simulated payout LRN-PAY-SEED0001 for USD ${seededPayout.amount.toFixed(2)} is waiting for admin review.`,
            link: "/instructor/earnings",
            eventKey: `payout-requested:${seededPayout.id}`,
          },
        ],
        skipDuplicates: true,
      });
    }

    // Generic announcements (one read, one unread) so every role's notification centre has content.
    for (const user of [sara, elena, adminUser]) {
      if (!user) continue;
      await prisma.notification.createMany({
        data: [
          {
            userId: user.id,
            type: "SYSTEM",
            title: "Welcome to Learnora",
            message:
              "Your notification centre shows payments, course updates, payouts and replies.",
            link: null,
            eventKey: "seed:welcome",
            readAt: new Date(),
          },
          {
            userId: user.id,
            type: "ANNOUNCEMENT",
            title: "Messaging is here",
            message: "Students can now message the instructor of any course they are enrolled in.",
            link: null,
            eventKey: "seed:messaging-announcement",
          },
        ],
        skipDuplicates: true,
      });
    }
  }

  console.log(
    `Seed complete: ${categories.size} categories, ${courses.length} courses (${publishedCourses.length} published).`,
  );
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
