/**
 * Development/sample database seed.
 *
 * This is sample data for local development only — it exists so the real
 * database has something to query while the frontend still reads from
 * src/data/mock.ts for the parts not yet migrated. It intentionally
 * mirrors that mock data's flavor (same categories/instructors feel)
 * without being a 1:1 copy, and it does NOT replace mock.ts yet.
 *
 * Run with: npm run db:seed
 */
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";

// Generated by `npm run db:generate` — see prisma/schema.prisma.
import { PrismaClient } from "../src/generated/prisma/client";

// Seeding does a lot of sequential upserts; run it against the direct
// connection to avoid any pooler/transaction-mode quirks, falling back to
// DATABASE_URL for setups with no separate pooled connection.
const connectionString = process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"];
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

async function hash(password: string) {
  return bcrypt.hash(password, 10);
}

const REVIEW_COMMENTS: Record<number, string[]> = {
  5: [
    "Clear explanations and practical examples throughout.",
    "Best course I've taken on this topic — genuinely changed how I work.",
    "The projects made everything click. Highly recommend.",
  ],
  4: [
    "Solid course overall, a couple of sections could go deeper.",
    "Well structured and easy to follow at my own pace.",
  ],
  3: ["Good content but the pacing felt uneven in places."],
  2: ["Useful information but assumed more prior knowledge than advertised."],
};

function ratingFor(studentIndex: number, courseIndex: number): number {
  const pattern = [5, 4, 5, 3, 4, 5, 5, 4, 2, 5, 4, 5];
  return pattern[(studentIndex * 5 + courseIndex * 3) % pattern.length] ?? 5;
}

async function main() {
  console.log("Seeding Learnora database...");

  // -- Categories ----------------------------------------------------------
  const categoryDefs = [
    {
      slug: "web-development",
      name: "Web Development",
      description: "Frontend to full-stack",
      icon: "Code2",
    },
    {
      slug: "programming",
      name: "Programming",
      description: "Languages and fundamentals",
      icon: "Terminal",
    },
    {
      slug: "data-science",
      name: "Data Science",
      description: "Statistics, Python, ML",
      icon: "LineChart",
    },
    {
      slug: "design",
      name: "UI / UX Design",
      description: "Research to design systems",
      icon: "PenTool",
    },
    {
      slug: "business",
      name: "Business",
      description: "Strategy and leadership",
      icon: "Briefcase",
    },
  ];
  const categories = new Map<string, Awaited<ReturnType<typeof prisma.category.upsert>>>();
  for (const def of categoryDefs) {
    const category = await prisma.category.upsert({
      where: { slug: def.slug },
      update: {},
      create: def,
    });
    categories.set(def.slug, category);
  }

  // -- Admin -----------------------------------------------------------------
  await prisma.user.upsert({
    where: { email: "admin@learnora.dev" },
    update: {},
    create: {
      name: "Amina Rahman",
      email: "admin@learnora.dev",
      passwordHash: await hash("Admin123!"),
      role: "ADMIN",
      emailVerified: true,
    },
  });

  // -- Instructors -------------------------------------------------------
  const instructorDefs = [
    {
      email: "elena.vasquez@learnora.dev",
      name: "Elena Vasquez",
      headline: "Principal Frontend Engineer, Meridian Labs",
      bio: "Twelve years building interface platforms for design-led product teams. Leads the frontend guild at Meridian Labs.",
      expertise: ["React", "TypeScript", "Design Systems"],
      approvalStatus: "APPROVED" as const,
    },
    {
      email: "marcus.chen@learnora.dev",
      name: "Marcus Chen",
      headline: "Staff Data Scientist",
      bio: "Focused on applied machine learning and statistics education, with a decade in production ML systems.",
      expertise: ["Python", "Machine Learning", "Statistics"],
      approvalStatus: "APPROVED" as const,
    },
    {
      email: "priyanka.das@learnora.dev",
      name: "Priyanka Das",
      headline: "Backend Engineer",
      bio: "Applied for instructor access recently — still awaiting admin approval.",
      expertise: ["Node.js", "Databases"],
      approvalStatus: "PENDING" as const,
    },
  ];
  const instructors = [];
  for (const def of instructorDefs) {
    const user = await prisma.user.upsert({
      where: { email: def.email },
      update: {},
      create: {
        name: def.name,
        email: def.email,
        passwordHash: await hash("Instructor123!"),
        role: "INSTRUCTOR",
        emailVerified: true,
        instructorProfile: {
          create: {
            headline: def.headline,
            bio: def.bio,
            expertise: def.expertise,
            approvalStatus: def.approvalStatus,
            approvedAt: def.approvalStatus === "APPROVED" ? new Date() : null,
          },
        },
      },
    });
    instructors.push(user);
  }
  const [elena, marcus] = instructors;

  // -- Students ------------------------------------------------------------
  const studentDefs = [
    { email: "sara.khan@learnora.dev", name: "Sara Khan", headline: "Frontend Developer" },
    { email: "james.oconnor@learnora.dev", name: "James O'Connor", headline: "Product Manager" },
    { email: "priya.nair@learnora.dev", name: "Priya Nair", headline: "Data Analyst" },
  ];
  const students = [];
  for (const def of studentDefs) {
    const user = await prisma.user.upsert({
      where: { email: def.email },
      update: {},
      create: {
        name: def.name,
        email: def.email,
        passwordHash: await hash("Student123!"),
        role: "STUDENT",
        emailVerified: true,
        studentProfile: {
          create: { headline: def.headline, interests: ["Web Development", "Data Science"] },
        },
      },
    });
    students.push(user);
  }

  // -- Courses, sections, lessons ------------------------------------------
  type LessonDef = {
    title: string;
    type: "VIDEO" | "ARTICLE" | "QUIZ";
    duration: number;
    isPreview?: boolean;
  };
  type SectionDef = { title: string; lessons: LessonDef[] };
  type CourseDef = {
    slug: string;
    title: string;
    subtitle: string;
    categorySlug: string;
    instructorId: string;
    level: "BEGINNER" | "INTERMEDIATE" | "ADVANCED" | "ALL_LEVELS";
    status: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "REJECTED";
    rejectionReason?: string;
    featured: boolean;
    price: number;
    discountPrice?: number;
    sections: SectionDef[];
  };

  const courseDefs: CourseDef[] = [
    {
      slug: "modern-react-typescript",
      title: "Modern React & TypeScript",
      subtitle: "Build production interfaces with confident types and clean state.",
      categorySlug: "web-development",
      instructorId: elena!.id,
      level: "INTERMEDIATE",
      status: "PUBLISHED",
      featured: true,
      price: 79.99,
      discountPrice: 49.99,
      sections: [
        {
          title: "Getting Started",
          lessons: [
            { title: "Course Overview", type: "VIDEO", duration: 300, isPreview: true },
            { title: "Environment Setup", type: "VIDEO", duration: 480 },
          ],
        },
        {
          title: "Component Patterns",
          lessons: [
            { title: "Typed Props & Children", type: "VIDEO", duration: 620 },
            { title: "Knowledge Check", type: "QUIZ", duration: 300 },
          ],
        },
      ],
    },
    {
      slug: "advanced-typescript-patterns",
      title: "Advanced TypeScript Patterns",
      subtitle: "Generics, conditional types and building type-safe APIs.",
      categorySlug: "web-development",
      instructorId: elena!.id,
      level: "ADVANCED",
      status: "PUBLISHED",
      featured: false,
      price: 94.99,
      sections: [
        {
          title: "Type-Level Programming",
          lessons: [
            { title: "Conditional & Mapped Types", type: "VIDEO", duration: 720, isPreview: true },
            { title: "Building a Type-Safe Router", type: "VIDEO", duration: 900 },
          ],
        },
      ],
    },
    {
      slug: "programming-fundamentals-js",
      title: "Programming Fundamentals with JavaScript",
      subtitle: "Variables, control flow and functions — the real foundation.",
      categorySlug: "programming",
      instructorId: elena!.id,
      level: "BEGINNER",
      status: "PUBLISHED",
      featured: false,
      price: 0,
      sections: [
        {
          title: "The Basics",
          lessons: [
            { title: "Values & Variables", type: "VIDEO", duration: 360, isPreview: true },
            { title: "Functions & Scope", type: "VIDEO", duration: 480 },
            { title: "Practice Quiz", type: "QUIZ", duration: 240 },
          ],
        },
      ],
    },
    {
      slug: "python-for-data-science",
      title: "Python for Data Science",
      subtitle: "From pandas basics to your first ML model.",
      categorySlug: "data-science",
      instructorId: marcus!.id,
      level: "BEGINNER",
      status: "PUBLISHED",
      featured: true,
      price: 34.99,
      sections: [
        {
          title: "Python Foundations",
          lessons: [
            { title: "Why Python for Data", type: "VIDEO", duration: 360, isPreview: true },
            { title: "NumPy & pandas Basics", type: "VIDEO", duration: 900 },
          ],
        },
      ],
    },
    {
      slug: "machine-learning-foundations",
      title: "Machine Learning Foundations",
      subtitle: "Core algorithms and how to evaluate them honestly.",
      categorySlug: "data-science",
      instructorId: marcus!.id,
      level: "INTERMEDIATE",
      status: "PUBLISHED",
      featured: false,
      price: 64.99,
      sections: [
        {
          title: "Supervised Learning",
          lessons: [
            {
              title: "Regression vs Classification",
              type: "VIDEO",
              duration: 540,
              isPreview: true,
            },
            { title: "Model Evaluation", type: "ARTICLE", duration: 300 },
          ],
        },
      ],
    },
    {
      slug: "design-systems-fundamentals",
      title: "Design Systems Fundamentals",
      subtitle: "Tokens, components and documentation that scale.",
      categorySlug: "design",
      instructorId: elena!.id,
      level: "INTERMEDIATE",
      status: "PUBLISHED",
      featured: true,
      price: 84.99,
      discountPrice: 59.99,
      sections: [
        {
          title: "Foundations",
          lessons: [
            { title: "Design Tokens", type: "VIDEO", duration: 420, isPreview: true },
            { title: "Component API Design", type: "VIDEO", duration: 600 },
          ],
        },
      ],
    },
    {
      slug: "product-strategy-for-engineers",
      title: "Product Strategy for Engineers",
      subtitle: "Make better roadmap and prioritisation calls.",
      categorySlug: "business",
      instructorId: marcus!.id,
      level: "ALL_LEVELS",
      status: "PUBLISHED",
      featured: false,
      price: 44.99,
      sections: [
        {
          title: "Thinking in Bets",
          lessons: [
            { title: "Prioritisation Frameworks", type: "VIDEO", duration: 480, isPreview: true },
            { title: "Writing a One-Pager", type: "ARTICLE", duration: 240 },
          ],
        },
      ],
    },
    {
      slug: "ux-research-methods",
      title: "UX Research Methods",
      subtitle: "Interviews, usability testing and turning findings into decisions.",
      categorySlug: "design",
      instructorId: marcus!.id,
      level: "BEGINNER",
      status: "DRAFT",
      featured: false,
      price: 39.99,
      sections: [
        {
          title: "Planning Research",
          lessons: [{ title: "Choosing a Method", type: "VIDEO", duration: 360, isPreview: true }],
        },
      ],
    },
    {
      slug: "node-backend-fundamentals",
      title: "Node.js Backend Fundamentals",
      subtitle: "REST APIs, authentication and database design with Node.js.",
      categorySlug: "web-development",
      instructorId: elena!.id,
      level: "INTERMEDIATE",
      status: "PENDING_REVIEW",
      featured: false,
      price: 54.99,
      sections: [
        {
          title: "Building the API",
          lessons: [
            { title: "Setting Up Express", type: "VIDEO", duration: 420, isPreview: true },
            { title: "Connecting a Database", type: "VIDEO", duration: 540 },
          ],
        },
      ],
    },
    {
      slug: "intro-to-figma",
      title: "Intro to Figma",
      subtitle: "Design your first interface from scratch.",
      categorySlug: "design",
      instructorId: elena!.id,
      level: "BEGINNER",
      status: "REJECTED",
      rejectionReason:
        "The curriculum only has one short lesson — please add a full set of sections covering the basics through to a complete design project before resubmitting.",
      featured: false,
      price: 29.99,
      sections: [
        {
          title: "Getting Started",
          lessons: [
            { title: "The Figma Interface", type: "VIDEO", duration: 300, isPreview: true },
          ],
        },
      ],
    },
  ];

  const courses = [];
  for (const def of courseDefs) {
    const category = categories.get(def.categorySlug)!;
    const course = await prisma.course.upsert({
      where: { slug: def.slug },
      update: {},
      create: {
        title: def.title,
        slug: def.slug,
        subtitle: def.subtitle,
        description: def.subtitle,
        level: def.level,
        price: def.price,
        ...(def.discountPrice !== undefined && { discountPrice: def.discountPrice }),
        status: def.status,
        publishedAt: def.status === "PUBLISHED" ? new Date() : null,
        submittedAt:
          def.status === "PENDING_REVIEW" || def.status === "REJECTED" ? new Date() : null,
        rejectionReason:
          def.status === "REJECTED" ? (def.rejectionReason ?? "Needs more work.") : null,
        featured: def.featured,
        requirements: ["Basic computer literacy"],
        learningOutcomes: ["Build real projects", "Understand core concepts"],
        targetAudience: ["Beginners", "Career switchers"],
        instructor: { connect: { id: def.instructorId } },
        category: { connect: { id: category.id } },
        sections: {
          create: def.sections.map((section, sectionIndex) => ({
            title: section.title,
            position: sectionIndex,
            lessons: {
              create: section.lessons.map((lesson, lessonIndex) => ({
                title: lesson.title,
                type: lesson.type,
                duration: lesson.duration,
                position: lessonIndex,
                isPreview: lesson.isPreview ?? false,
              })),
            },
          })),
        },
      },
    });
    courses.push({ ...course, status: def.status });
  }

  // -- Enrollments & reviews (published courses only) ----------------------
  const publishedCourses = courses.filter((c) => c.status === "PUBLISHED");
  for (let studentIndex = 0; studentIndex < students.length; studentIndex++) {
    const student = students[studentIndex]!;
    for (let courseIndex = 0; courseIndex < publishedCourses.length; courseIndex++) {
      const course = publishedCourses[courseIndex]!;

      await prisma.enrollment.upsert({
        where: { userId_courseId: { userId: student.id, courseId: course.id } },
        update: {},
        create: { userId: student.id, courseId: course.id },
      });

      const rating = ratingFor(studentIndex, courseIndex);
      const comments = REVIEW_COMMENTS[rating] ?? REVIEW_COMMENTS[5]!;
      const comment = comments[courseIndex % comments.length]!;

      await prisma.review.upsert({
        where: { userId_courseId: { userId: student.id, courseId: course.id } },
        update: {},
        create: { userId: student.id, courseId: course.id, rating, comment },
      });
    }
  }

  // -- Lesson progress: give a couple of students realistic in-progress /
  // completed states so My Learning and the course player have something
  // to show beyond "0% everywhere". ------------------------------------
  const sara = students[0]!;
  const james = students[1]!;
  // priya (students[2]) is left with zero lesson progress on purpose, to
  // exercise the "not started yet" state.

  async function lessonsOf(courseId: string) {
    const sections = await prisma.courseSection.findMany({
      where: { courseId },
      orderBy: { position: "asc" },
      include: { lessons: { orderBy: { position: "asc" } } },
    });
    return sections.flatMap((s) => s.lessons);
  }

  const reactCourse = publishedCourses.find((c) => c.slug === "modern-react-typescript");
  const pythonCourse = publishedCourses.find((c) => c.slug === "python-for-data-science");
  const advancedTsCourse = publishedCourses.find((c) => c.slug === "advanced-typescript-patterns");

  if (reactCourse) {
    // Sara has finished this course entirely.
    const lessons = await lessonsOf(reactCourse.id);
    const enrollment = await prisma.enrollment.findUniqueOrThrow({
      where: { userId_courseId: { userId: sara.id, courseId: reactCourse.id } },
    });
    for (const lesson of lessons) {
      await prisma.lessonProgress.upsert({
        where: { enrollmentId_lessonId: { enrollmentId: enrollment.id, lessonId: lesson.id } },
        update: {},
        create: {
          enrollmentId: enrollment.id,
          lessonId: lesson.id,
          completed: true,
          progressPercent: 100,
        },
      });
    }
    await prisma.enrollment.update({
      where: { id: enrollment.id },
      data: { status: "COMPLETED", completedAt: new Date(), lastAccessedAt: new Date() },
    });
  }

  if (pythonCourse) {
    // Sara is partway through this one — completed the first lesson only.
    const lessons = await lessonsOf(pythonCourse.id);
    const first = lessons[0];
    const enrollment = await prisma.enrollment.findUniqueOrThrow({
      where: { userId_courseId: { userId: sara.id, courseId: pythonCourse.id } },
    });
    if (first) {
      await prisma.lessonProgress.upsert({
        where: { enrollmentId_lessonId: { enrollmentId: enrollment.id, lessonId: first.id } },
        update: {},
        create: {
          enrollmentId: enrollment.id,
          lessonId: first.id,
          completed: true,
          progressPercent: 100,
        },
      });
    }
    await prisma.enrollment.update({
      where: { id: enrollment.id },
      data: { lastAccessedAt: new Date() },
    });
  }

  if (advancedTsCourse) {
    // James has just started this one.
    const lessons = await lessonsOf(advancedTsCourse.id);
    const first = lessons[0];
    const enrollment = await prisma.enrollment.findUniqueOrThrow({
      where: { userId_courseId: { userId: james.id, courseId: advancedTsCourse.id } },
    });
    if (first) {
      await prisma.lessonProgress.upsert({
        where: { enrollmentId_lessonId: { enrollmentId: enrollment.id, lessonId: first.id } },
        update: {},
        create: {
          enrollmentId: enrollment.id,
          lessonId: first.id,
          completed: true,
          progressPercent: 100,
        },
      });
    }
    await prisma.enrollment.update({
      where: { id: enrollment.id },
      data: { lastAccessedAt: new Date() },
    });
  }

  // -- Wishlist --------------------------------------------------------------
  const wishlistDefs: { student: (typeof students)[number]; slug: string }[] = [
    { student: sara, slug: "design-systems-fundamentals" },
    { student: sara, slug: "machine-learning-foundations" },
    { student: james, slug: "python-for-data-science" },
  ];
  for (const def of wishlistDefs) {
    const course = publishedCourses.find((c) => c.slug === def.slug);
    if (!course) continue;
    await prisma.wishlist.upsert({
      where: { userId_courseId: { userId: def.student.id, courseId: course.id } },
      update: {},
      create: { userId: def.student.id, courseId: course.id },
    });
  }

  console.log(
    `Seed complete: ${categories.size} categories, ${courses.length} courses (${publishedCourses.length} published).`,
  );
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
