import { PrismaPg } from "@prisma/adapter-pg";

import { getServerEnv } from "../env";
// Generated by `npm run db:generate` from prisma/schema.prisma — see the
// `output` path on the `generator client` block in that file. This path
// does not exist until generate has been run at least once.
import { PrismaClient } from "../../generated/prisma/client";

/**
 * Singleton Prisma client.
 *
 * Vite's dev server hot-reloads server modules, which would otherwise
 * construct a brand new PrismaClient (and a brand new connection pool, and
 * a brand new pg.Pool underneath the adapter) on every edit. We stash the
 * instance on `globalThis` in development so repeated reloads reuse the
 * same client; production always gets a fresh singleton per process.
 */
declare global {
  var __learnoraPrisma: PrismaClient | undefined;
}

function createPrismaClient() {
  const env = getServerEnv();
  // Prisma ORM 7 requires an explicit driver adapter — this is the app's
  // runtime connection and should be the *pooled* connection string
  // (e.g. Neon's "-pooler" host). Prisma CLI commands (migrate, db push)
  // use a separate direct connection configured in prisma.config.ts.
  const adapter = new PrismaPg({ connectionString: env.DATABASE_URL });
  return new PrismaClient({
    adapter,
    log: env.NODE_ENV === "development" ? ["warn", "error"] : ["error"],
  });
}

export const prisma = globalThis.__learnoraPrisma ?? createPrismaClient();

if (process.env["NODE_ENV"] !== "production") {
  globalThis.__learnoraPrisma = prisma;
}
