/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BecomeInstructorRouteImport } from './routes/become-instructor'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StudentRouteImport } from './routes/student'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCourseApprovalRouteImport } from './routes/admin.course-approval'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin.enrollments'
import { Route as AdminInstructorsRouteImport } from './routes/admin.instructors'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiEventsRouteImport } from './routes/api.events'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiReadyRouteImport } from './routes/api.ready'
import { Route as CheckoutCourseIdRouteImport } from './routes/checkout.$courseId'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as InstructorIndexRouteImport } from './routes/instructor.index'
import { Route as InstructorAnalyticsRouteImport } from './routes/instructor.analytics'
import { Route as InstructorDashboardRouteImport } from './routes/instructor.dashboard'
import { Route as InstructorEarningsRouteImport } from './routes/instructor.earnings'
import { Route as InstructorMessagesRouteImport } from './routes/instructor.messages'
import { Route as InstructorNotificationsRouteImport } from './routes/instructor.notifications'
import { Route as InstructorProfileRouteImport } from './routes/instructor.profile'
import { Route as InstructorReviewsRouteImport } from './routes/instructor.reviews'
import { Route as InstructorSettingsRouteImport } from './routes/instructor.settings'
import { Route as InstructorStudentsRouteImport } from './routes/instructor.students'
import { Route as InstructorsInstructorIdRouteImport } from './routes/instructors.$instructorId'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentLearningRouteImport } from './routes/student.learning'
import { Route as StudentMessagesRouteImport } from './routes/student.messages'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentPurchasesRouteImport } from './routes/student.purchases'
import { Route as StudentSettingsRouteImport } from './routes/student.settings'
import { Route as StudentWishlistRouteImport } from './routes/student.wishlist'
import { Route as ApiAccountAvatarRouteImport } from './routes/api.account.avatar'
import { Route as ApiCronCleanupUploadsRouteImport } from './routes/api.cron.cleanup-uploads'
import { Route as ApiMediaUploadFinalizeRouteImport } from './routes/api.media.upload-finalize'
import { Route as ApiMediaUploadIntentRouteImport } from './routes/api.media.upload-intent'
import { Route as CertificatesVerifyIndexRouteImport } from './routes/certificates.verify.index'
import { Route as CertificatesVerifyCodeRouteImport } from './routes/certificates.verify.$code'
import { Route as CheckoutSuccessOrderIdRouteImport } from './routes/checkout.success.$orderId'
import { Route as InstructorCoursesIndexRouteImport } from './routes/instructor.courses.index'
import { Route as InstructorCoursesCourseIdRouteImport } from './routes/instructor.courses.$courseId'
import { Route as InstructorCoursesCreateRouteImport } from './routes/instructor.courses.create'
import { Route as MediaLessonVideoAssetIdRouteImport } from './routes/media.lesson-video.$assetId'
import { Route as MediaPublicAssetIdRouteImport } from './routes/media.public.$assetId'
import { Route as MediaResourceAssetIdRouteImport } from './routes/media.resource.$assetId'
import { Route as StudentCertificatesIndexRouteImport } from './routes/student.certificates.index'
import { Route as StudentCertificatesCertificateIdRouteImport } from './routes/student.certificates.$certificateId'
import { Route as StudentCourseCourseIdRouteImport } from './routes/student.course.$courseId'
import { Route as ApiInstructorMediaPreviewCourseIdRouteImport } from './routes/api.instructor.media.preview.$courseId'
import { Route as ApiInstructorMediaThumbnailCourseIdRouteImport } from './routes/api.instructor.media.thumbnail.$courseId'
import { Route as ApiInstructorMediaLessonResourceCourseIdLessonIdRouteImport } from './routes/api.instructor.media.lesson-resource.$courseId.$lessonId'
import { Route as ApiInstructorMediaLessonVideoCourseIdLessonIdRouteImport } from './routes/api.instructor.media.lesson-video.$courseId.$lessonId'
import { Route as ApiInstructorMediaResourceCourseIdLessonIdResourceIdRouteImport } from './routes/api.instructor.media.resource.$courseId.$lessonId.$resourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeInstructorRoute = BecomeInstructorRouteImport.update({
  id: '/become-instructor',
  path: '/become-instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCourseApprovalRoute = AdminCourseApprovalRouteImport.update({
  id: '/course-approval',
  path: '/course-approval',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstructorsRoute = AdminInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCourseIdRoute = CheckoutCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CheckoutRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorAnalyticsRoute = InstructorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorDashboardRoute = InstructorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorEarningsRoute = InstructorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorMessagesRoute = InstructorMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorNotificationsRoute = InstructorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorProfileRoute = InstructorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorReviewsRoute = InstructorReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorSettingsRoute = InstructorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorStudentsRoute = InstructorStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorsInstructorIdRoute = InstructorsInstructorIdRouteImport.update({
  id: '/instructors/$instructorId',
  path: '/instructors/$instructorId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLearningRoute = StudentLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPurchasesRoute = StudentPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentWishlistRoute = StudentWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => StudentRoute,
} as any)
const ApiAccountAvatarRoute = ApiAccountAvatarRouteImport.update({
  id: '/api/account/avatar',
  path: '/api/account/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronCleanupUploadsRoute = ApiCronCleanupUploadsRouteImport.update({
  id: '/api/cron/cleanup-uploads',
  path: '/api/cron/cleanup-uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadFinalizeRoute = ApiMediaUploadFinalizeRouteImport.update({
  id: '/api/media/upload-finalize',
  path: '/api/media/upload-finalize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadIntentRoute = ApiMediaUploadIntentRouteImport.update({
  id: '/api/media/upload-intent',
  path: '/api/media/upload-intent',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesVerifyIndexRoute = CertificatesVerifyIndexRouteImport.update({
  id: '/certificates/verify/',
  path: '/certificates/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesVerifyCodeRoute = CertificatesVerifyCodeRouteImport.update({
  id: '/certificates/verify/$code',
  path: '/certificates/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessOrderIdRoute = CheckoutSuccessOrderIdRouteImport.update({
  id: '/success/$orderId',
  path: '/success/$orderId',
  getParentRoute: () => CheckoutRoute,
} as any)
const InstructorCoursesIndexRoute = InstructorCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorCoursesCourseIdRoute =
  InstructorCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => InstructorRoute,
  } as any)
const InstructorCoursesCreateRoute = InstructorCoursesCreateRouteImport.update({
  id: '/courses/create',
  path: '/courses/create',
  getParentRoute: () => InstructorRoute,
} as any)
const MediaLessonVideoAssetIdRoute = MediaLessonVideoAssetIdRouteImport.update({
  id: '/media/lesson-video/$assetId',
  path: '/media/lesson-video/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaPublicAssetIdRoute = MediaPublicAssetIdRouteImport.update({
  id: '/media/public/$assetId',
  path: '/media/public/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaResourceAssetIdRoute = MediaResourceAssetIdRouteImport.update({
  id: '/media/resource/$assetId',
  path: '/media/resource/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCertificatesIndexRoute =
  StudentCertificatesIndexRouteImport.update({
    id: '/certificates/',
    path: '/certificates/',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentCertificatesCertificateIdRoute =
  StudentCertificatesCertificateIdRouteImport.update({
    id: '/certificates/$certificateId',
    path: '/certificates/$certificateId',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentCourseCourseIdRoute = StudentCourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => StudentRoute,
} as any)
const ApiInstructorMediaPreviewCourseIdRoute =
  ApiInstructorMediaPreviewCourseIdRouteImport.update({
    id: '/api/instructor/media/preview/$courseId',
    path: '/api/instructor/media/preview/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInstructorMediaThumbnailCourseIdRoute =
  ApiInstructorMediaThumbnailCourseIdRouteImport.update({
    id: '/api/instructor/media/thumbnail/$courseId',
    path: '/api/instructor/media/thumbnail/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInstructorMediaLessonResourceCourseIdLessonIdRoute =
  ApiInstructorMediaLessonResourceCourseIdLessonIdRouteImport.update({
    id: '/api/instructor/media/lesson-resource/$courseId/$lessonId',
    path: '/api/instructor/media/lesson-resource/$courseId/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInstructorMediaLessonVideoCourseIdLessonIdRoute =
  ApiInstructorMediaLessonVideoCourseIdLessonIdRouteImport.update({
    id: '/api/instructor/media/lesson-video/$courseId/$lessonId',
    path: '/api/instructor/media/lesson-video/$courseId/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInstructorMediaResourceCourseIdLessonIdResourceIdRoute =
  ApiInstructorMediaResourceCourseIdLessonIdResourceIdRouteImport.update({
    id: '/api/instructor/media/resource/$courseId/$lessonId/$resourceId',
    path: '/api/instructor/media/resource/$courseId/$lessonId/$resourceId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-instructor': typeof BecomeInstructorRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/instructor': typeof InstructorRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/course-approval': typeof AdminCourseApprovalRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/checkout/$courseId': typeof CheckoutCourseIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/earnings': typeof InstructorEarningsRoute
  '/instructor/messages': typeof InstructorMessagesRoute
  '/instructor/notifications': typeof InstructorNotificationsRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/reviews': typeof InstructorReviewsRoute
  '/instructor/settings': typeof InstructorSettingsRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/instructors/$instructorId': typeof InstructorsInstructorIdRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/learning': typeof StudentLearningRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/purchases': typeof StudentPurchasesRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/wishlist': typeof StudentWishlistRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/api/account/avatar': typeof ApiAccountAvatarRoute
  '/api/cron/cleanup-uploads': typeof ApiCronCleanupUploadsRoute
  '/api/media/upload-finalize': typeof ApiMediaUploadFinalizeRoute
  '/api/media/upload-intent': typeof ApiMediaUploadIntentRoute
  '/certificates/verify/$code': typeof CertificatesVerifyCodeRoute
  '/checkout/success/$orderId': typeof CheckoutSuccessOrderIdRoute
  '/instructor/courses/$courseId': typeof InstructorCoursesCourseIdRoute
  '/instructor/courses/create': typeof InstructorCoursesCreateRoute
  '/media/lesson-video/$assetId': typeof MediaLessonVideoAssetIdRoute
  '/media/public/$assetId': typeof MediaPublicAssetIdRoute
  '/media/resource/$assetId': typeof MediaResourceAssetIdRoute
  '/student/certificates/$certificateId': typeof StudentCertificatesCertificateIdRoute
  '/student/course/$courseId': typeof StudentCourseCourseIdRoute
  '/certificates/verify/': typeof CertificatesVerifyIndexRoute
  '/instructor/courses/': typeof InstructorCoursesIndexRoute
  '/student/certificates/': typeof StudentCertificatesIndexRoute
  '/api/instructor/media/preview/$courseId': typeof ApiInstructorMediaPreviewCourseIdRoute
  '/api/instructor/media/thumbnail/$courseId': typeof ApiInstructorMediaThumbnailCourseIdRoute
  '/api/instructor/media/lesson-resource/$courseId/$lessonId': typeof ApiInstructorMediaLessonResourceCourseIdLessonIdRoute
  '/api/instructor/media/lesson-video/$courseId/$lessonId': typeof ApiInstructorMediaLessonVideoCourseIdLessonIdRoute
  '/api/instructor/media/resource/$courseId/$lessonId/$resourceId': typeof ApiInstructorMediaResourceCourseIdLessonIdResourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-instructor': typeof BecomeInstructorRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/course-approval': typeof AdminCourseApprovalRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/checkout/$courseId': typeof CheckoutCourseIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/earnings': typeof InstructorEarningsRoute
  '/instructor/messages': typeof InstructorMessagesRoute
  '/instructor/notifications': typeof InstructorNotificationsRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/reviews': typeof InstructorReviewsRoute
  '/instructor/settings': typeof InstructorSettingsRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/instructors/$instructorId': typeof InstructorsInstructorIdRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/learning': typeof StudentLearningRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/purchases': typeof StudentPurchasesRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/wishlist': typeof StudentWishlistRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/instructor': typeof InstructorIndexRoute
  '/student': typeof StudentIndexRoute
  '/api/account/avatar': typeof ApiAccountAvatarRoute
  '/api/cron/cleanup-uploads': typeof ApiCronCleanupUploadsRoute
  '/api/media/upload-finalize': typeof ApiMediaUploadFinalizeRoute
  '/api/media/upload-intent': typeof ApiMediaUploadIntentRoute
  '/certificates/verify/$code': typeof CertificatesVerifyCodeRoute
  '/checkout/success/$orderId': typeof CheckoutSuccessOrderIdRoute
  '/instructor/courses/$courseId': typeof InstructorCoursesCourseIdRoute
  '/instructor/courses/create': typeof InstructorCoursesCreateRoute
  '/media/lesson-video/$assetId': typeof MediaLessonVideoAssetIdRoute
  '/media/public/$assetId': typeof MediaPublicAssetIdRoute
  '/media/resource/$assetId': typeof MediaResourceAssetIdRoute
  '/student/certificates/$certificateId': typeof StudentCertificatesCertificateIdRoute
  '/student/course/$courseId': typeof StudentCourseCourseIdRoute
  '/certificates/verify': typeof CertificatesVerifyIndexRoute
  '/instructor/courses': typeof InstructorCoursesIndexRoute
  '/student/certificates': typeof StudentCertificatesIndexRoute
  '/api/instructor/media/preview/$courseId': typeof ApiInstructorMediaPreviewCourseIdRoute
  '/api/instructor/media/thumbnail/$courseId': typeof ApiInstructorMediaThumbnailCourseIdRoute
  '/api/instructor/media/lesson-resource/$courseId/$lessonId': typeof ApiInstructorMediaLessonResourceCourseIdLessonIdRoute
  '/api/instructor/media/lesson-video/$courseId/$lessonId': typeof ApiInstructorMediaLessonVideoCourseIdLessonIdRoute
  '/api/instructor/media/resource/$courseId/$lessonId/$resourceId': typeof ApiInstructorMediaResourceCourseIdLessonIdResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-instructor': typeof BecomeInstructorRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/instructor': typeof InstructorRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/course-approval': typeof AdminCourseApprovalRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/checkout/$courseId': typeof CheckoutCourseIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/earnings': typeof InstructorEarningsRoute
  '/instructor/messages': typeof InstructorMessagesRoute
  '/instructor/notifications': typeof InstructorNotificationsRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/reviews': typeof InstructorReviewsRoute
  '/instructor/settings': typeof InstructorSettingsRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/instructors/$instructorId': typeof InstructorsInstructorIdRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/learning': typeof StudentLearningRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/purchases': typeof StudentPurchasesRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/wishlist': typeof StudentWishlistRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/api/account/avatar': typeof ApiAccountAvatarRoute
  '/api/cron/cleanup-uploads': typeof ApiCronCleanupUploadsRoute
  '/api/media/upload-finalize': typeof ApiMediaUploadFinalizeRoute
  '/api/media/upload-intent': typeof ApiMediaUploadIntentRoute
  '/certificates/verify/$code': typeof CertificatesVerifyCodeRoute
  '/checkout/success/$orderId': typeof CheckoutSuccessOrderIdRoute
  '/instructor/courses/$courseId': typeof InstructorCoursesCourseIdRoute
  '/instructor/courses/create': typeof InstructorCoursesCreateRoute
  '/media/lesson-video/$assetId': typeof MediaLessonVideoAssetIdRoute
  '/media/public/$assetId': typeof MediaPublicAssetIdRoute
  '/media/resource/$assetId': typeof MediaResourceAssetIdRoute
  '/student/certificates/$certificateId': typeof StudentCertificatesCertificateIdRoute
  '/student/course/$courseId': typeof StudentCourseCourseIdRoute
  '/certificates/verify/': typeof CertificatesVerifyIndexRoute
  '/instructor/courses/': typeof InstructorCoursesIndexRoute
  '/student/certificates/': typeof StudentCertificatesIndexRoute
  '/api/instructor/media/preview/$courseId': typeof ApiInstructorMediaPreviewCourseIdRoute
  '/api/instructor/media/thumbnail/$courseId': typeof ApiInstructorMediaThumbnailCourseIdRoute
  '/api/instructor/media/lesson-resource/$courseId/$lessonId': typeof ApiInstructorMediaLessonResourceCourseIdLessonIdRoute
  '/api/instructor/media/lesson-video/$courseId/$lessonId': typeof ApiInstructorMediaLessonVideoCourseIdLessonIdRoute
  '/api/instructor/media/resource/$courseId/$lessonId/$resourceId': typeof ApiInstructorMediaResourceCourseIdLessonIdResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/become-instructor'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/instructor'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/terms'
    | '/admin/categories'
    | '/admin/course-approval'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/instructors'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/students'
    | '/admin/users'
    | '/api/events'
    | '/api/health'
    | '/api/ready'
    | '/checkout/$courseId'
    | '/courses/$courseId'
    | '/instructor/analytics'
    | '/instructor/dashboard'
    | '/instructor/earnings'
    | '/instructor/messages'
    | '/instructor/notifications'
    | '/instructor/profile'
    | '/instructor/reviews'
    | '/instructor/settings'
    | '/instructor/students'
    | '/instructors/$instructorId'
    | '/student/dashboard'
    | '/student/learning'
    | '/student/messages'
    | '/student/notifications'
    | '/student/profile'
    | '/student/purchases'
    | '/student/settings'
    | '/student/wishlist'
    | '/admin/'
    | '/courses/'
    | '/instructor/'
    | '/student/'
    | '/api/account/avatar'
    | '/api/cron/cleanup-uploads'
    | '/api/media/upload-finalize'
    | '/api/media/upload-intent'
    | '/certificates/verify/$code'
    | '/checkout/success/$orderId'
    | '/instructor/courses/$courseId'
    | '/instructor/courses/create'
    | '/media/lesson-video/$assetId'
    | '/media/public/$assetId'
    | '/media/resource/$assetId'
    | '/student/certificates/$certificateId'
    | '/student/course/$courseId'
    | '/certificates/verify/'
    | '/instructor/courses/'
    | '/student/certificates/'
    | '/api/instructor/media/preview/$courseId'
    | '/api/instructor/media/thumbnail/$courseId'
    | '/api/instructor/media/lesson-resource/$courseId/$lessonId'
    | '/api/instructor/media/lesson-video/$courseId/$lessonId'
    | '/api/instructor/media/resource/$courseId/$lessonId/$resourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-instructor'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/admin/categories'
    | '/admin/course-approval'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/instructors'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/students'
    | '/admin/users'
    | '/api/events'
    | '/api/health'
    | '/api/ready'
    | '/checkout/$courseId'
    | '/courses/$courseId'
    | '/instructor/analytics'
    | '/instructor/dashboard'
    | '/instructor/earnings'
    | '/instructor/messages'
    | '/instructor/notifications'
    | '/instructor/profile'
    | '/instructor/reviews'
    | '/instructor/settings'
    | '/instructor/students'
    | '/instructors/$instructorId'
    | '/student/dashboard'
    | '/student/learning'
    | '/student/messages'
    | '/student/notifications'
    | '/student/profile'
    | '/student/purchases'
    | '/student/settings'
    | '/student/wishlist'
    | '/admin'
    | '/courses'
    | '/instructor'
    | '/student'
    | '/api/account/avatar'
    | '/api/cron/cleanup-uploads'
    | '/api/media/upload-finalize'
    | '/api/media/upload-intent'
    | '/certificates/verify/$code'
    | '/checkout/success/$orderId'
    | '/instructor/courses/$courseId'
    | '/instructor/courses/create'
    | '/media/lesson-video/$assetId'
    | '/media/public/$assetId'
    | '/media/resource/$assetId'
    | '/student/certificates/$certificateId'
    | '/student/course/$courseId'
    | '/certificates/verify'
    | '/instructor/courses'
    | '/student/certificates'
    | '/api/instructor/media/preview/$courseId'
    | '/api/instructor/media/thumbnail/$courseId'
    | '/api/instructor/media/lesson-resource/$courseId/$lessonId'
    | '/api/instructor/media/lesson-video/$courseId/$lessonId'
    | '/api/instructor/media/resource/$courseId/$lessonId/$resourceId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/become-instructor'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/instructor'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/terms'
    | '/admin/categories'
    | '/admin/course-approval'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/instructors'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/students'
    | '/admin/users'
    | '/api/events'
    | '/api/health'
    | '/api/ready'
    | '/checkout/$courseId'
    | '/courses/$courseId'
    | '/instructor/analytics'
    | '/instructor/dashboard'
    | '/instructor/earnings'
    | '/instructor/messages'
    | '/instructor/notifications'
    | '/instructor/profile'
    | '/instructor/reviews'
    | '/instructor/settings'
    | '/instructor/students'
    | '/instructors/$instructorId'
    | '/student/dashboard'
    | '/student/learning'
    | '/student/messages'
    | '/student/notifications'
    | '/student/profile'
    | '/student/purchases'
    | '/student/settings'
    | '/student/wishlist'
    | '/admin/'
    | '/courses/'
    | '/instructor/'
    | '/student/'
    | '/api/account/avatar'
    | '/api/cron/cleanup-uploads'
    | '/api/media/upload-finalize'
    | '/api/media/upload-intent'
    | '/certificates/verify/$code'
    | '/checkout/success/$orderId'
    | '/instructor/courses/$courseId'
    | '/instructor/courses/create'
    | '/media/lesson-video/$assetId'
    | '/media/public/$assetId'
    | '/media/resource/$assetId'
    | '/student/certificates/$certificateId'
    | '/student/course/$courseId'
    | '/certificates/verify/'
    | '/instructor/courses/'
    | '/student/certificates/'
    | '/api/instructor/media/preview/$courseId'
    | '/api/instructor/media/thumbnail/$courseId'
    | '/api/instructor/media/lesson-resource/$courseId/$lessonId'
    | '/api/instructor/media/lesson-video/$courseId/$lessonId'
    | '/api/instructor/media/resource/$courseId/$lessonId/$resourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BecomeInstructorRoute: typeof BecomeInstructorRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  InstructorRoute: typeof InstructorRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudentRoute: typeof StudentRouteWithChildren
  TermsRoute: typeof TermsRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadyRoute: typeof ApiReadyRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  InstructorsInstructorIdRoute: typeof InstructorsInstructorIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiAccountAvatarRoute: typeof ApiAccountAvatarRoute
  ApiCronCleanupUploadsRoute: typeof ApiCronCleanupUploadsRoute
  ApiMediaUploadFinalizeRoute: typeof ApiMediaUploadFinalizeRoute
  ApiMediaUploadIntentRoute: typeof ApiMediaUploadIntentRoute
  CertificatesVerifyCodeRoute: typeof CertificatesVerifyCodeRoute
  MediaLessonVideoAssetIdRoute: typeof MediaLessonVideoAssetIdRoute
  MediaPublicAssetIdRoute: typeof MediaPublicAssetIdRoute
  MediaResourceAssetIdRoute: typeof MediaResourceAssetIdRoute
  CertificatesVerifyIndexRoute: typeof CertificatesVerifyIndexRoute
  ApiInstructorMediaPreviewCourseIdRoute: typeof ApiInstructorMediaPreviewCourseIdRoute
  ApiInstructorMediaThumbnailCourseIdRoute: typeof ApiInstructorMediaThumbnailCourseIdRoute
  ApiInstructorMediaLessonResourceCourseIdLessonIdRoute: typeof ApiInstructorMediaLessonResourceCourseIdLessonIdRoute
  ApiInstructorMediaLessonVideoCourseIdLessonIdRoute: typeof ApiInstructorMediaLessonVideoCourseIdLessonIdRoute
  ApiInstructorMediaResourceCourseIdLessonIdResourceIdRoute: typeof ApiInstructorMediaResourceCourseIdLessonIdResourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-instructor': {
      id: '/become-instructor'
      path: '/become-instructor'
      fullPath: '/become-instructor'
      preLoaderRoute: typeof BecomeInstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/course-approval': {
      id: '/admin/course-approval'
      path: '/course-approval'
      fullPath: '/admin/course-approval'
      preLoaderRoute: typeof AdminCourseApprovalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instructors': {
      id: '/admin/instructors'
      path: '/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof AdminInstructorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$courseId': {
      id: '/checkout/$courseId'
      path: '/$courseId'
      fullPath: '/checkout/$courseId'
      preLoaderRoute: typeof CheckoutCourseIdRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/analytics': {
      id: '/instructor/analytics'
      path: '/analytics'
      fullPath: '/instructor/analytics'
      preLoaderRoute: typeof InstructorAnalyticsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/dashboard': {
      id: '/instructor/dashboard'
      path: '/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof InstructorDashboardRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/earnings': {
      id: '/instructor/earnings'
      path: '/earnings'
      fullPath: '/instructor/earnings'
      preLoaderRoute: typeof InstructorEarningsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/messages': {
      id: '/instructor/messages'
      path: '/messages'
      fullPath: '/instructor/messages'
      preLoaderRoute: typeof InstructorMessagesRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/notifications': {
      id: '/instructor/notifications'
      path: '/notifications'
      fullPath: '/instructor/notifications'
      preLoaderRoute: typeof InstructorNotificationsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/profile': {
      id: '/instructor/profile'
      path: '/profile'
      fullPath: '/instructor/profile'
      preLoaderRoute: typeof InstructorProfileRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/reviews': {
      id: '/instructor/reviews'
      path: '/reviews'
      fullPath: '/instructor/reviews'
      preLoaderRoute: typeof InstructorReviewsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/settings': {
      id: '/instructor/settings'
      path: '/settings'
      fullPath: '/instructor/settings'
      preLoaderRoute: typeof InstructorSettingsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/students': {
      id: '/instructor/students'
      path: '/students'
      fullPath: '/instructor/students'
      preLoaderRoute: typeof InstructorStudentsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructors/$instructorId': {
      id: '/instructors/$instructorId'
      path: '/instructors/$instructorId'
      fullPath: '/instructors/$instructorId'
      preLoaderRoute: typeof InstructorsInstructorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/learning': {
      id: '/student/learning'
      path: '/learning'
      fullPath: '/student/learning'
      preLoaderRoute: typeof StudentLearningRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/purchases': {
      id: '/student/purchases'
      path: '/purchases'
      fullPath: '/student/purchases'
      preLoaderRoute: typeof StudentPurchasesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/wishlist': {
      id: '/student/wishlist'
      path: '/wishlist'
      fullPath: '/student/wishlist'
      preLoaderRoute: typeof StudentWishlistRouteImport
      parentRoute: typeof StudentRoute
    }
    '/api/account/avatar': {
      id: '/api/account/avatar'
      path: '/api/account/avatar'
      fullPath: '/api/account/avatar'
      preLoaderRoute: typeof ApiAccountAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/cleanup-uploads': {
      id: '/api/cron/cleanup-uploads'
      path: '/api/cron/cleanup-uploads'
      fullPath: '/api/cron/cleanup-uploads'
      preLoaderRoute: typeof ApiCronCleanupUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload-finalize': {
      id: '/api/media/upload-finalize'
      path: '/api/media/upload-finalize'
      fullPath: '/api/media/upload-finalize'
      preLoaderRoute: typeof ApiMediaUploadFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload-intent': {
      id: '/api/media/upload-intent'
      path: '/api/media/upload-intent'
      fullPath: '/api/media/upload-intent'
      preLoaderRoute: typeof ApiMediaUploadIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/verify/': {
      id: '/certificates/verify/'
      path: '/certificates/verify'
      fullPath: '/certificates/verify/'
      preLoaderRoute: typeof CertificatesVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/verify/$code': {
      id: '/certificates/verify/$code'
      path: '/certificates/verify/$code'
      fullPath: '/certificates/verify/$code'
      preLoaderRoute: typeof CertificatesVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success/$orderId': {
      id: '/checkout/success/$orderId'
      path: '/success/$orderId'
      fullPath: '/checkout/success/$orderId'
      preLoaderRoute: typeof CheckoutSuccessOrderIdRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/instructor/courses/': {
      id: '/instructor/courses/'
      path: '/courses'
      fullPath: '/instructor/courses/'
      preLoaderRoute: typeof InstructorCoursesIndexRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/courses/$courseId': {
      id: '/instructor/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/instructor/courses/$courseId'
      preLoaderRoute: typeof InstructorCoursesCourseIdRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/courses/create': {
      id: '/instructor/courses/create'
      path: '/courses/create'
      fullPath: '/instructor/courses/create'
      preLoaderRoute: typeof InstructorCoursesCreateRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/media/lesson-video/$assetId': {
      id: '/media/lesson-video/$assetId'
      path: '/media/lesson-video/$assetId'
      fullPath: '/media/lesson-video/$assetId'
      preLoaderRoute: typeof MediaLessonVideoAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/public/$assetId': {
      id: '/media/public/$assetId'
      path: '/media/public/$assetId'
      fullPath: '/media/public/$assetId'
      preLoaderRoute: typeof MediaPublicAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/resource/$assetId': {
      id: '/media/resource/$assetId'
      path: '/media/resource/$assetId'
      fullPath: '/media/resource/$assetId'
      preLoaderRoute: typeof MediaResourceAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/certificates/': {
      id: '/student/certificates/'
      path: '/certificates'
      fullPath: '/student/certificates/'
      preLoaderRoute: typeof StudentCertificatesIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/certificates/$certificateId': {
      id: '/student/certificates/$certificateId'
      path: '/certificates/$certificateId'
      fullPath: '/student/certificates/$certificateId'
      preLoaderRoute: typeof StudentCertificatesCertificateIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/course/$courseId': {
      id: '/student/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/student/course/$courseId'
      preLoaderRoute: typeof StudentCourseCourseIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/api/instructor/media/preview/$courseId': {
      id: '/api/instructor/media/preview/$courseId'
      path: '/api/instructor/media/preview/$courseId'
      fullPath: '/api/instructor/media/preview/$courseId'
      preLoaderRoute: typeof ApiInstructorMediaPreviewCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instructor/media/thumbnail/$courseId': {
      id: '/api/instructor/media/thumbnail/$courseId'
      path: '/api/instructor/media/thumbnail/$courseId'
      fullPath: '/api/instructor/media/thumbnail/$courseId'
      preLoaderRoute: typeof ApiInstructorMediaThumbnailCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instructor/media/lesson-resource/$courseId/$lessonId': {
      id: '/api/instructor/media/lesson-resource/$courseId/$lessonId'
      path: '/api/instructor/media/lesson-resource/$courseId/$lessonId'
      fullPath: '/api/instructor/media/lesson-resource/$courseId/$lessonId'
      preLoaderRoute: typeof ApiInstructorMediaLessonResourceCourseIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instructor/media/lesson-video/$courseId/$lessonId': {
      id: '/api/instructor/media/lesson-video/$courseId/$lessonId'
      path: '/api/instructor/media/lesson-video/$courseId/$lessonId'
      fullPath: '/api/instructor/media/lesson-video/$courseId/$lessonId'
      preLoaderRoute: typeof ApiInstructorMediaLessonVideoCourseIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instructor/media/resource/$courseId/$lessonId/$resourceId': {
      id: '/api/instructor/media/resource/$courseId/$lessonId/$resourceId'
      path: '/api/instructor/media/resource/$courseId/$lessonId/$resourceId'
      fullPath: '/api/instructor/media/resource/$courseId/$lessonId/$resourceId'
      preLoaderRoute: typeof ApiInstructorMediaResourceCourseIdLessonIdResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCourseApprovalRoute: typeof AdminCourseApprovalRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminInstructorsRoute: typeof AdminInstructorsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCourseApprovalRoute: AdminCourseApprovalRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminInstructorsRoute: AdminInstructorsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutCourseIdRoute: typeof CheckoutCourseIdRoute
  CheckoutSuccessOrderIdRoute: typeof CheckoutSuccessOrderIdRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutCourseIdRoute: CheckoutCourseIdRoute,
  CheckoutSuccessOrderIdRoute: CheckoutSuccessOrderIdRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface InstructorRouteChildren {
  InstructorAnalyticsRoute: typeof InstructorAnalyticsRoute
  InstructorDashboardRoute: typeof InstructorDashboardRoute
  InstructorEarningsRoute: typeof InstructorEarningsRoute
  InstructorMessagesRoute: typeof InstructorMessagesRoute
  InstructorNotificationsRoute: typeof InstructorNotificationsRoute
  InstructorProfileRoute: typeof InstructorProfileRoute
  InstructorReviewsRoute: typeof InstructorReviewsRoute
  InstructorSettingsRoute: typeof InstructorSettingsRoute
  InstructorStudentsRoute: typeof InstructorStudentsRoute
  InstructorIndexRoute: typeof InstructorIndexRoute
  InstructorCoursesCourseIdRoute: typeof InstructorCoursesCourseIdRoute
  InstructorCoursesCreateRoute: typeof InstructorCoursesCreateRoute
  InstructorCoursesIndexRoute: typeof InstructorCoursesIndexRoute
}

const InstructorRouteChildren: InstructorRouteChildren = {
  InstructorAnalyticsRoute: InstructorAnalyticsRoute,
  InstructorDashboardRoute: InstructorDashboardRoute,
  InstructorEarningsRoute: InstructorEarningsRoute,
  InstructorMessagesRoute: InstructorMessagesRoute,
  InstructorNotificationsRoute: InstructorNotificationsRoute,
  InstructorProfileRoute: InstructorProfileRoute,
  InstructorReviewsRoute: InstructorReviewsRoute,
  InstructorSettingsRoute: InstructorSettingsRoute,
  InstructorStudentsRoute: InstructorStudentsRoute,
  InstructorIndexRoute: InstructorIndexRoute,
  InstructorCoursesCourseIdRoute: InstructorCoursesCourseIdRoute,
  InstructorCoursesCreateRoute: InstructorCoursesCreateRoute,
  InstructorCoursesIndexRoute: InstructorCoursesIndexRoute,
}

const InstructorRouteWithChildren = InstructorRoute._addFileChildren(
  InstructorRouteChildren,
)

interface StudentRouteChildren {
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentLearningRoute: typeof StudentLearningRoute
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentPurchasesRoute: typeof StudentPurchasesRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentWishlistRoute: typeof StudentWishlistRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentCertificatesCertificateIdRoute: typeof StudentCertificatesCertificateIdRoute
  StudentCourseCourseIdRoute: typeof StudentCourseCourseIdRoute
  StudentCertificatesIndexRoute: typeof StudentCertificatesIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDashboardRoute: StudentDashboardRoute,
  StudentLearningRoute: StudentLearningRoute,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentPurchasesRoute: StudentPurchasesRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentWishlistRoute: StudentWishlistRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentCertificatesCertificateIdRoute: StudentCertificatesCertificateIdRoute,
  StudentCourseCourseIdRoute: StudentCourseCourseIdRoute,
  StudentCertificatesIndexRoute: StudentCertificatesIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BecomeInstructorRoute: BecomeInstructorRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  InstructorRoute: InstructorRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudentRoute: StudentRouteWithChildren,
  TermsRoute: TermsRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadyRoute: ApiReadyRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  InstructorsInstructorIdRoute: InstructorsInstructorIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiAccountAvatarRoute: ApiAccountAvatarRoute,
  ApiCronCleanupUploadsRoute: ApiCronCleanupUploadsRoute,
  ApiMediaUploadFinalizeRoute: ApiMediaUploadFinalizeRoute,
  ApiMediaUploadIntentRoute: ApiMediaUploadIntentRoute,
  CertificatesVerifyCodeRoute: CertificatesVerifyCodeRoute,
  MediaLessonVideoAssetIdRoute: MediaLessonVideoAssetIdRoute,
  MediaPublicAssetIdRoute: MediaPublicAssetIdRoute,
  MediaResourceAssetIdRoute: MediaResourceAssetIdRoute,
  CertificatesVerifyIndexRoute: CertificatesVerifyIndexRoute,
  ApiInstructorMediaPreviewCourseIdRoute:
    ApiInstructorMediaPreviewCourseIdRoute,
  ApiInstructorMediaThumbnailCourseIdRoute:
    ApiInstructorMediaThumbnailCourseIdRoute,
  ApiInstructorMediaLessonResourceCourseIdLessonIdRoute:
    ApiInstructorMediaLessonResourceCourseIdLessonIdRoute,
  ApiInstructorMediaLessonVideoCourseIdLessonIdRoute:
    ApiInstructorMediaLessonVideoCourseIdLessonIdRoute,
  ApiInstructorMediaResourceCourseIdLessonIdResourceIdRoute:
    ApiInstructorMediaResourceCourseIdLessonIdResourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
